export interface TemplateContext {
  projectName: string;
  projectId: string;
  techStack: string[];
  entities: {
    pages: Array<{ name: string; path?: string; description?: string }>;
    apis: Array<{ path: string; method: string; description?: string }>;
    dbTables: Array<{ name: string; description?: string }>;
    envVars: Array<{ name: string; description?: string; required?: boolean }>;
    integrations: Array<{ name: string; description?: string }>;
  };
  findings: Array<{ severity: string; title: string; description?: string }>;
}

export function generateReadme(context: TemplateContext): string {
  const { projectName, techStack, entities, findings } = context;

  const badgeStack = techStack
    .map((t) => {
      const slug = t.toLowerCase().replace(/\s+/g, '-');
      return `![${t}](https://img.shields.io/badge/${encodeURIComponent(t)}-informational?style=flat&logo=${slug})`;
    })
    .join(' ');

  const criticalFindings = findings.filter((f) => f.severity === 'critical').length;
  const highFindings = findings.filter((f) => f.severity === 'high').length;

  const techStackSection =
    techStack.length > 0
      ? techStack.map((t) => `- ${t}`).join('\n')
      : '- No tech stack detected';

  const pagesList =
    entities.pages.length > 0
      ? entities.pages.map((p) => `- **${p.name}** — ${p.description ?? p.path ?? ''}`).join('\n')
      : '- No pages detected';

  const integrationsList =
    entities.integrations.length > 0
      ? entities.integrations
          .map((i) => `- **${i.name}** — ${i.description ?? ''}`)
          .join('\n')
      : '- No external integrations detected';

  const findingsSummary =
    findings.length > 0
      ? `> ⚠️ **${criticalFindings} critical** and **${highFindings} high** severity findings detected. See the [architecture doc](./architecture.md) for details.`
      : '> ✅ No critical findings detected.';

  return `# ${projectName}

${badgeStack}

${findingsSummary}

## Description

${projectName} is an automatically documented project analysed by Triefrog. This README was generated from a live snapshot of the codebase.

## Quick Start

\`\`\`bash
# Clone the repository
git clone <repo-url>
cd <repo-name>

# Install dependencies
pnpm install

# Copy environment variables
cp .env.example .env

# Start development servers
pnpm dev
\`\`\`

See [setup.md](./setup.md) for detailed setup instructions.

## Tech Stack

${techStackSection}

## Architecture Overview

${projectName} follows a modular architecture. Key components:

${pagesList}

### External Integrations

${integrationsList}

For a full architecture breakdown, see [architecture.md](./architecture.md).

## Documentation

| Document | Description |
|----------|-------------|
| [Setup](./setup.md) | Prerequisites, environment variables, local development |
| [Architecture](./architecture.md) | System design, entities, data flow |
| [API Reference](./api.md) | Endpoint listing, auth, request/response examples |
| [Data Model](./data-model.md) | Database tables, relationships, migrations |
| [Deploy](./deploy.md) | Deployment targets, production env vars, steps |
| [Runbook](./runbook.md) | Health checks, restart procedures, monitoring |

## Contributing

1. Create a feature branch from \`main\`
2. Make your changes and write tests
3. Run \`pnpm test\` and \`pnpm lint\`
4. Open a pull request

---

*Generated by [Triefrog](https://triefrog.dev) — auto-documentation for modern teams.*
`;
}
