import type { TemplateContext } from './readme.template';

export function generateSetup(context: TemplateContext): string {
  const { projectName, techStack, entities } = context;

  const envVarRows =
    entities.envVars.length > 0
      ? entities.envVars
          .map(
            (v) =>
              `| \`${v.name}\` | ${v.description ?? ''} | ${v.required ? 'Required' : 'Optional'} |`,
          )
          .join('\n')
      : '| *(none detected)* | | |';

  const nodeVersion = techStack.some((t) => t.toLowerCase().includes('node'))
    ? '20.x'
    : '20.x';

  const hasPrisma = techStack.some((t) =>
    t.toLowerCase().includes('prisma'),
  );
  const hasDocker = techStack.some((t) =>
    t.toLowerCase().includes('docker'),
  );

  const dbSetupSteps = hasPrisma
    ? `### Database Setup (Prisma)

\`\`\`bash
# Apply migrations
pnpm prisma migrate dev

# (Optional) Seed the database
pnpm prisma db seed

# Open Prisma Studio
pnpm prisma studio
\`\`\``
    : `### Database Setup

Configure your database connection string in \`.env\` and run any required migrations.`;

  const dockerSection = hasDocker
    ? `### Using Docker Compose

\`\`\`bash
# Start all services
docker compose up -d

# View logs
docker compose logs -f

# Stop services
docker compose down
\`\`\``
    : '';

  return `# Setup Guide — ${projectName}

## Prerequisites

Before you begin, ensure you have the following installed:

| Tool | Version | Notes |
|------|---------|-------|
| Node.js | >= ${nodeVersion} | Use [nvm](https://github.com/nvm-sh/nvm) or [fnm](https://github.com/Schniz/fnm) |
| pnpm | >= 8.x | \`npm install -g pnpm\` |
| Git | >= 2.x | Required for version control |
| PostgreSQL | >= 15 | Or use Docker (see below) |
| Redis | >= 7 | Required for queues and caching |

## Environment Variables

Copy the example file and fill in your values:

\`\`\`bash
cp .env.example .env
\`\`\`

| Variable | Description | Required |
|----------|-------------|----------|
${envVarRows}

### Common Environment Variables

\`\`\`env
# Application
NODE_ENV=development
PORT=3000

# Database
DATABASE_URL=postgresql://user:password@localhost:5432/triefrog

# Redis
REDIS_HOST=localhost
REDIS_PORT=6379

# Auth
JWT_SECRET=your-super-secret-key-change-in-production
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d
\`\`\`

## Installation

\`\`\`bash
# Install all workspace dependencies
pnpm install

# Build shared packages
pnpm --filter @triefrog/shared-types build
pnpm --filter @triefrog/shared-utils build
\`\`\`

${dbSetupSteps}

${dockerSection}

## Running Locally

\`\`\`bash
# Start all services in watch mode
pnpm dev

# Or start individual services
pnpm --filter @triefrog/gateway dev
pnpm --filter @triefrog/docs-service dev
\`\`\`

### Verify the Setup

Once running, verify the services are healthy:

\`\`\`bash
# Gateway health check
curl http://localhost:3000/health

# Docs service health check
curl http://localhost:3006/health
\`\`\`

## Common Issues

### Port already in use

\`\`\`bash
# Find and kill the process using the port
lsof -ti:3000 | xargs kill -9
\`\`\`

### Prisma client out of date

\`\`\`bash
pnpm prisma generate
\`\`\`

### Redis connection refused

Ensure Redis is running:

\`\`\`bash
redis-server
# or via Docker
docker run -p 6379:6379 redis:7-alpine
\`\`\`

---

*Generated by [Triefrog](https://triefrog.dev)*
`;
}
