import type { TemplateContext } from './readme.template';

export function generateArchitecture(context: TemplateContext): string {
  const { projectName, techStack, entities, findings } = context;

  const pagesList =
    entities.pages.length > 0
      ? entities.pages
          .map((p) => `| ${p.name} | ${p.path ?? ''} | ${p.description ?? ''} |`)
          .join('\n')
      : '| *(none detected)* | | |';

  const apiList =
    entities.apis.length > 0
      ? entities.apis
          .map((a) => `| \`${a.method}\` | \`${a.path}\` | ${a.description ?? ''} |`)
          .join('\n')
      : '| *(none detected)* | | |';

  const dbTableList =
    entities.dbTables.length > 0
      ? entities.dbTables
          .map((t) => `| ${t.name} | ${t.description ?? ''} |`)
          .join('\n')
      : '| *(none detected)* | |';

  const integrationList =
    entities.integrations.length > 0
      ? entities.integrations
          .map((i) => `| ${i.name} | ${i.description ?? ''} |`)
          .join('\n')
      : '| *(none detected)* | |';

  const findingsSection =
    findings.length > 0
      ? `## Security & Quality Findings

| Severity | Title | Description |
|----------|-------|-------------|
${findings
  .map((f) => `| ${f.severity} | ${f.title} | ${f.description ?? ''} |`)
  .join('\n')}`
      : '';

  const techStackBullets = techStack.map((t) => `- ${t}`).join('\n');

  return `# Architecture — ${projectName}

## System Overview

${projectName} is a modern web application built with a microservices-inspired architecture. The system is decomposed into focused services communicating via HTTP and message queues, with a gateway (BFF) handling all client-facing traffic.

\`\`\`
┌─────────────┐     ┌─────────────┐     ┌──────────────────┐
│   Web App   │────▶│   Gateway   │────▶│  Auth Service    │
│  (Next.js)  │     │  (BFF :3000)│     │  (:3001)         │
└─────────────┘     │             │────▶│  Connector Svc   │
                    │             │     │  (:3002)         │
                    │             │────▶│  Scanner Svc     │
                    │             │     │  (:3003)         │
                    │             │────▶│  Graph Svc       │
                    │             │     │  (:3004)         │
                    │             │────▶│  Check Svc       │
                    │             │     │  (:3005)         │
                    │             │────▶│  Docs Svc        │
                    └─────────────┘     │  (:3006)         │
                                        └──────────────────┘
                                                │
                                        ┌───────▼────────┐
                                        │   PostgreSQL   │
                                        │   + Redis      │
                                        └────────────────┘
\`\`\`

## Technology Stack

${techStackBullets}

## Frontend Pages / Routes

| Page | Path | Description |
|------|------|-------------|
${pagesList}

## API Endpoints

| Method | Path | Description |
|--------|------|-------------|
${apiList}

## Database Tables

| Table | Description |
|-------|-------------|
${dbTableList}

## External Integrations

| Integration | Description |
|-------------|-------------|
${integrationList}

## Data Flow

### Authentication Flow

1. Client sends credentials to \`POST /auth/login\` via Gateway
2. Gateway proxies request to Auth Service
3. Auth Service validates credentials and issues JWT access + refresh tokens
4. Client includes \`Authorization: Bearer <token>\` on subsequent requests
5. Gateway validates JWT before forwarding to downstream services

### Scan & Documentation Flow

1. User triggers a scan via \`POST /projects/:id/scan\`
2. Scanner Service crawls the project codebase/repository
3. On completion, Scanner emits a \`snapshot.created\` event to Redis queue
4. Check Service and Docs Service consume the event
5. Check Service runs quality and security checks
6. Docs Service generates all 7 documentation types from templates
7. Results are available via their respective service APIs

### Real-time Updates

SSE streams are available at \`GET /projects/:id/scan/stream\` for live scan progress.

${findingsSection}

---

*Generated by [Triefrog](https://triefrog.dev)*
`;
}
