import type { TemplateContext } from './readme.template';

export function generateDataModel(context: TemplateContext): string {
  const { projectName, entities } = context;

  const tablesSection =
    entities.dbTables.length > 0
      ? entities.dbTables
          .map(
            (t) => `### \`${t.name}\`

${t.description ?? `Stores ${t.name.toLowerCase()} records.`}

| Column | Type | Description |
|--------|------|-------------|
| \`id\` | \`uuid\` | Primary key |
| \`created_at\` | \`timestamptz\` | Record creation timestamp |
| \`updated_at\` | \`timestamptz\` | Last update timestamp |
`,
          )
          .join('\n')
      : '*(No database tables detected — run a scan to populate this section)*';

  return `# Data Model — ${projectName}

## Overview

This document describes the database schema for ${projectName}. The application uses **PostgreSQL** as its primary data store, managed via **Prisma ORM**.

## Core Tables

${tablesSection}

## Triefrog Internal Schema

The following tables are used by Triefrog to store scan results and documentation metadata:

### \`projects\`

Represents a scanned project.

| Column | Type | Description |
|--------|------|-------------|
| \`id\` | \`uuid\` | Primary key |
| \`org_id\` | \`uuid\` | Foreign key to \`organisations\` |
| \`name\` | \`text\` | Human-readable project name |
| \`repo_url\` | \`text\` | Source repository URL |
| \`status\` | \`text\` | \`active\` \| \`archived\` |
| \`created_at\` | \`timestamptz\` | Record creation timestamp |
| \`updated_at\` | \`timestamptz\` | Last update timestamp |

### \`snapshots\`

A point-in-time scan of a project.

| Column | Type | Description |
|--------|------|-------------|
| \`id\` | \`uuid\` | Primary key |
| \`project_id\` | \`uuid\` | Foreign key to \`projects\` |
| \`status\` | \`text\` | \`pending\` \| \`running\` \| \`complete\` \| \`failed\` |
| \`started_at\` | \`timestamptz\` | Scan start time |
| \`completed_at\` | \`timestamptz\` | Scan completion time |

### \`entities\`

Individual detected entities (pages, APIs, DB tables, env vars, integrations).

| Column | Type | Description |
|--------|------|-------------|
| \`id\` | \`uuid\` | Primary key |
| \`snapshot_id\` | \`uuid\` | Foreign key to \`snapshots\` |
| \`type\` | \`text\` | Entity category |
| \`name\` | \`text\` | Entity name |
| \`metadata\` | \`jsonb\` | Additional entity-specific data |

### \`docs\`

Generated documentation files.

| Column | Type | Description |
|--------|------|-------------|
| \`id\` | \`uuid\` | Primary key |
| \`project_id\` | \`uuid\` | Foreign key to \`projects\` |
| \`type\` | \`text\` | Doc type: \`readme\`, \`setup\`, \`architecture\`, \`deploy\`, \`api\`, \`data-model\`, \`runbook\` |
| \`title\` | \`text\` | Display title |
| \`status\` | \`text\` | \`draft\` \| \`verified\` |
| \`last_verified_at\` | \`timestamptz\` | When a human last verified this doc |
| \`created_at\` | \`timestamptz\` | Record creation timestamp |
| \`updated_at\` | \`timestamptz\` | Last update timestamp |

### \`doc_versions\`

Immutable content versions for each doc (append-only log).

| Column | Type | Description |
|--------|------|-------------|
| \`id\` | \`uuid\` | Primary key |
| \`doc_id\` | \`uuid\` | Foreign key to \`docs\` |
| \`content\` | \`text\` | Markdown content |
| \`created_at\` | \`timestamptz\` | Version creation timestamp |

### \`findings\`

Quality and security findings from the check service.

| Column | Type | Description |
|--------|------|-------------|
| \`id\` | \`uuid\` | Primary key |
| \`project_id\` | \`uuid\` | Foreign key to \`projects\` |
| \`snapshot_id\` | \`uuid\` | Foreign key to \`snapshots\` |
| \`severity\` | \`text\` | \`critical\` \| \`high\` \| \`medium\` \| \`low\` \| \`info\` |
| \`title\` | \`text\` | Short finding title |
| \`description\` | \`text\` | Full description |
| \`resolved_at\` | \`timestamptz\` | When this finding was resolved |

## Relationships

\`\`\`
organisations ──< projects ──< snapshots ──< entities
                    │              │
                    └──< docs ──< doc_versions
                    │
                    └──< findings
\`\`\`

## Migration Notes

- Migrations are managed by **Prisma Migrate**
- Always run \`pnpm prisma migrate deploy\` on deployment
- Never edit migration files after they have been applied to any environment
- Use \`pnpm prisma migrate dev\` locally to generate new migrations
- Breaking schema changes must be deployed in multiple phases (expand/contract pattern)

---

*Generated by [Triefrog](https://triefrog.dev)*
`;
}
