import type { TemplateContext } from './readme.template';

export function generateDeploy(context: TemplateContext): string {
  const { projectName, entities } = context;

  const prodEnvVars =
    entities.envVars.length > 0
      ? entities.envVars
          .filter((v) => v.required)
          .map((v) => `| \`${v.name}\` | ${v.description ?? ''} |`)
          .join('\n')
      : '| *(none detected)* | |';

  return `# Deployment Guide — ${projectName}

## Deployment Targets

| Environment | Platform | URL |
|-------------|----------|-----|
| Production | Vercel / Railway / Fly.io | \`https://app.example.com\` |
| Staging | Same platform | \`https://staging.example.com\` |
| Preview | Per-branch | Auto-generated |

## Required Environment Variables (Production)

The following environment variables must be set in your deployment platform before deploying:

| Variable | Description |
|----------|-------------|
${prodEnvVars}
| \`NODE_ENV\` | Set to \`production\` |
| \`DATABASE_URL\` | Production database connection string |
| \`REDIS_URL\` | Production Redis connection string |
| \`JWT_SECRET\` | Strong random secret (min 32 chars) |

## Pre-Deployment Checklist

- [ ] All environment variables configured in deployment platform
- [ ] Database migrations reviewed and tested
- [ ] Smoke tests passing on staging
- [ ] Rollback plan documented and tested
- [ ] Monitoring and alerting configured
- [ ] SSL/TLS certificates valid

## Deployment Steps

### 1. Build

\`\`\`bash
# Install dependencies
pnpm install --frozen-lockfile

# Build all packages and apps
pnpm build
\`\`\`

### 2. Database Migration

\`\`\`bash
# Run migrations (never skip in production)
pnpm prisma migrate deploy
\`\`\`

### 3. Deploy Services

\`\`\`bash
# Using Railway CLI
railway up

# Or using Docker
docker compose -f docker-compose.prod.yml up -d --build
\`\`\`

### 4. Health Checks

\`\`\`bash
# Verify all services are healthy
curl https://api.example.com/health
curl https://api.example.com/docs-service/health
\`\`\`

## Rollback Procedure

### Immediate Rollback (Code)

\`\`\`bash
# Identify the previous good deployment tag
git tag -l | tail -5

# Revert to previous version
git checkout v<previous-version>
pnpm build
# Re-deploy using your platform's redeploy mechanism
\`\`\`

### Database Rollback

\`\`\`bash
# List applied migrations
pnpm prisma migrate status

# Roll back the last migration (use with caution)
pnpm prisma migrate resolve --rolled-back <migration-name>
\`\`\`

> **Warning:** Database rollbacks may result in data loss. Always take a snapshot before deploying schema changes.

## Zero-Downtime Deployment

The services support rolling deployments. Ensure:

1. New version is backwards-compatible with the current database schema
2. At least 2 replicas are running during the cutover
3. Load balancer health checks are configured

## Monitoring

After deployment, verify:

- [ ] Error rate is below baseline
- [ ] P95 response time is within SLA
- [ ] No unusual memory or CPU spikes
- [ ] Queue depths are draining normally

---

*Generated by [Triefrog](https://triefrog.dev)*
`;
}
